<a href="https://colab.research.google.com/github/ShihanZENG/Awesome-DSDO/blob/main/%E2%80%9CClean_and_prepare_data_ipynb%E2%80%9D%E7%9A%84%E5%89%AF%E6%9C%AC1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [39]:
#customers_datase
customers_datase= pd.read_csv('olist_customers_dataset.csv')
#customers_datase.drop(['customer_unique_id','customer_zip_code_prefix'],axis=1, inplace=True)
#customers_datase.head()

#olist_order_reviews_dataset
reviews_dataset= pd.read_csv('olist_order_reviews_dataset.csv')
#reviews_dataset.drop(['review_id','review_comment_title','review_comment_message','review_creation_date','review_answer_timestamp'],axis=1, inplace=True)
#reviews_dataset.head()

# items_dataset
items_dataset= pd.read_csv('olist_order_items_dataset.csv')
#items_dataset.drop(['shipping_limit_date','order_item_id','seller_id'],axis=1, inplace=True)
#items_dataset.head()

#olist_order_payments_dataset
payments_dataset= pd.read_csv('olist_order_payments_dataset.csv')
#payments_dataset.drop(['payment_sequential'],axis=1, inplace=True)
#payments_dataset.head()

#orders_dataset# main
order_dataset= pd.read_csv('olist_orders_dataset.csv')
#order_dataset.drop(['order_approved_at','order_delivered_carrier_date','order_approved_at'],axis=1, inplace=True)
#order_dataset.head()

#olist_products_dataset
products_dataset= pd.read_csv('olist_products_dataset.csv')
#products_dataset.drop(['product_name_lenght','product_description_lenght','product_photos_qty','product_weight_g','product_length_cm','product_height_cm','product_width_cm'],axis=1, inplace=True)
#products_dataset.drop(['product_name_lenght','product_description_lenght','product_length_cm','product_height_cm','product_width_cm'],axis=1, inplace=True)
#products_dataset.head()

df = order_dataset.copy()
df = df.merge(items_dataset, on='order_id', how='left')
df = df.merge(reviews_dataset, on='order_id', how='left')
df = df.merge(customers_datase, on='customer_id', how='left')
df = df.merge(payments_dataset, on='order_id', how='left')
df = df.merge(products_dataset, on='product_id', how='left')
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,payment_installments,payment_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,1.0,18.12,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,1.0,2.00,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,1.0,18.59,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,595fac2a385ac33a80bd5114aec74eb8,...,1.0,141.46,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,aa4383b373c6aca5d8797843e5594415,...,3.0,179.12,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119006,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1.0,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,3.0,195.00,bebes,52.0,828.0,4.0,4950.0,40.0,10.0,40.0
119007,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1.0,b80910977a37536adeddd63663f916ad,...,5.0,271.01,eletrodomesticos_2,51.0,500.0,2.0,13300.0,32.0,90.0,22.0
119008,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,1.0,d1c427060a0f73f6b889a5c7c61f2ac4,...,4.0,441.16,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
119009,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2.0,d1c427060a0f73f6b889a5c7c61f2ac4,...,4.0,441.16,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
119010,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,006619bbed68b000c8ba3f8725d5409e,...,1.0,86.86,beleza_saude,45.0,569.0,1.0,150.0,16.0,7.0,15.0

Remove unnecessary variable columns

In [40]:
df.drop(['customer_zip_code_prefix','review_comment_title','review_comment_message','review_creation_date','review_answer_timestamp','shipping_limit_date','order_item_id','seller_id','order_approved_at','order_delivered_carrier_date','order_approved_at','product_name_lenght','product_length_cm','product_height_cm','product_width_cm','product_weight_g'],axis=1, inplace=True)
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,product_id,price,freight_value,review_id,review_score,customer_unique_id,customer_region,payment_sequential,payment_type,payment_installments,payment_value,product_category_name,product_description_lenght,product_photos_qty
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18 00:00:00,87285b34884572647811a353c7ac498a,29.99,8.72,a54f0611adc9ed256b57ede6b6eb5114,4.0,7c396fd4830fd04220f754e42b4e5bff,SP,1.0,credit_card,1.0,18.12,utilidades_domesticas,268.0,4.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18 00:00:00,87285b34884572647811a353c7ac498a,29.99,8.72,a54f0611adc9ed256b57ede6b6eb5114,4.0,7c396fd4830fd04220f754e42b4e5bff,SP,3.0,voucher,1.0,2.00,utilidades_domesticas,268.0,4.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18 00:00:00,87285b34884572647811a353c7ac498a,29.99,8.72,a54f0611adc9ed256b57ede6b6eb5114,4.0,7c396fd4830fd04220f754e42b4e5bff,SP,2.0,voucher,1.0,18.59,utilidades_domesticas,268.0,4.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-08-07 15:27:45,2018-08-13 00:00:00,595fac2a385ac33a80bd5114aec74eb8,118.70,22.76,8d5266042046a06655c8db133d120ba5,4.0,af07308b275d755c9edb36a90c618231,BA,1.0,boleto,1.0,141.46,perfumaria,178.0,1.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-17 18:06:29,2018-09-04 00:00:00,aa4383b373c6aca5d8797843e5594415,159.90,19.22,e73b67b67587f7644d5bd1a52deb1b01,5.0,3a653a41f6f9fc3d2a113cf8398680e8,GO,1.0,credit_card,3.0,179.12,automotivo,232.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119006,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-28 17:37:56,2018-03-02 00:00:00,f1d4ce8c6dd66c47bbaa8c6781c2a923,174.90,20.10,29bb71b2760d0f876dfa178a76bc4734,4.0,da62f9e57a76d978d02ab5362c509660,SP,1.0,credit_card,3.0,195.00,bebes,828.0,4.0
119007,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-09-21 11:24:17,2017-09-27 00:00:00,b80910977a37536adeddd63663f916ad,205.99,65.02,371579771219f6db2d830d50805977bb,5.0,737520a9aad80b3fbbdad19b66b37b30,BA,1.0,credit_card,5.0,271.01,eletrodomesticos_2,500.0,2.0
119008,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-25 23:32:54,2018-02-15 00:00:00,d1c427060a0f73f6b889a5c7c61f2ac4,179.99,40.59,8ab6855b9fe9b812cd03a480a25058a1,2.0,5097a5312c8b157bb7be58ae360ef43c,RJ,1.0,credit_card,4.0,441.16,informatica_acessorios,1893.0,1.0
119009,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-25 23:32:54,2018-02-15 00:00:00,d1c427060a0f73f6b889a5c7c61f2ac4,179.99,40.59,8ab6855b9fe9b812cd03a480a25058a1,2.0,5097a5312c8b157bb7be58ae360ef43c,RJ,1.0,credit_card,4.0,441.16,informatica_acessorios,1893.0,1.0
119010,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-16 13:08:30,2018-04-03 00:00:00,006619bbed68b000c8ba3f8725d5409e,68.50,18.36,dc9c59b4688062c25758c2be4cafc523,5.0,60350aa974b26ff12caad89e55993bd6,PR,1.0,debit_card,1.0,86.86,beleza_saude,569.0,1.0

In [41]:
df.to_csv('Joined_Dataframe.csv', sep=",")

Descriptive statistics (original consolidated large table)

In [ ]:
df.info()
df.describe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119011 entries, 0 to 119010
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119011 non-null  object
 1   customer_id                    119011 non-null  object
 2   order_status                   119011 non-null  object
 3   order_purchase_timestamp       119011 non-null  object
 4   order_delivered_customer_date  115595 non-null  object
 5   order_estimated_delivery_date  119011 non-null  object
 6   product_id                     118179 non-null  object
 7   price                          118179 non-null  float64
 8   freight_value                  118179 non-null  float64
 9   review_id                      107254 non-null  object
 10  review_score                   107254 non-null  float64
 11  customer_unique_id             119011 non-null  object
 12  customer_region                119011 non-null  object
 13  payment_sequential             119008 non-null  float64
 14  payment_type                   119008 non-null  object
 15  payment_installments           119008 non-null  float64
 16  payment_value                  119008 non-null  float64
 17  product_category_name          116470 non-null  object
 18  product_description_lenght     116470 non-null  float64
 19  product_photos_qty             116470 non-null  float64
dtypes: float64(8), object(12)
memory usage: 18.2+ MB

<bound method NDFrame.describe of                                 order_id                       customer_id  \
0       e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1       e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
2       e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
3       53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
4       47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
...                                  ...                               ...
119006  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7
119007  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c
119008  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
119009  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
119010  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24

       order_status order_purchase_timestamp order_delivered_customer_date  \
0         delivered      2017-10-02 10:56:33           2017-10-10 21:25:13
1         delivered      2017-10-02 10:56:33           2017-10-10 21:25:13
2         delivered      2017-10-02 10:56:33           2017-10-10 21:25:13
3         delivered      2018-07-24 20:41:37           2018-08-07 15:27:45
4         delivered      2018-08-08 08:38:49           2018-08-17 18:06:29
...             ...                      ...                           ...
119006    delivered      2018-02-06 12:58:58           2018-02-28 17:37:56
119007    delivered      2017-08-27 14:46:43           2017-09-21 11:24:17
119008    delivered      2018-01-08 21:28:27           2018-01-25 23:32:54
119009    delivered      2018-01-08 21:28:27           2018-01-25 23:32:54
119010    delivered      2018-03-08 20:57:30           2018-03-16 13:08:30

       order_estimated_delivery_date                        product_id  \
0                2017-10-18 00:00:00  87285b34884572647811a353c7ac498a
1                2017-10-18 00:00:00  87285b34884572647811a353c7ac498a
2                2017-10-18 00:00:00  87285b34884572647811a353c7ac498a
3                2018-08-13 00:00:00  595fac2a385ac33a80bd5114aec74eb8
4                2018-09-04 00:00:00  aa4383b373c6aca5d8797843e5594415
...                              ...                               ...
119006           2018-03-02 00:00:00  f1d4ce8c6dd66c47bbaa8c6781c2a923
119007           2017-09-27 00:00:00  b80910977a37536adeddd63663f916ad
119008           2018-02-15 00:00:00  d1c427060a0f73f6b889a5c7c61f2ac4
119009           2018-02-15 00:00:00  d1c427060a0f73f6b889a5c7c61f2ac4
119010           2018-04-03 00:00:00  006619bbed68b000c8ba3f8725d5409e

         price  freight_value                         review_id  review_score  \
0        29.99           8.72  a54f0611adc9ed256b57ede6b6eb5114           4.0
1        29.99           8.72  a54f0611adc9ed256b57ede6b6eb5114           4.0
2        29.99           8.72  a54f0611adc9ed256b57ede6b6eb5114           4.0
3       118.70          22.76  8d5266042046a06655c8db133d120ba5           4.0
4       159.90          19.22  e73b67b67587f7644d5bd1a52deb1b01           5.0
...        ...            ...                               ...           ...
119006  174.90          20.10  29bb71b2760d0f876dfa178a76bc4734           4.0
119007  205.99          65.02  371579771219f6db2d830d50805977bb           5.0
119008  179.99          40.59  8ab6855b9fe9b812cd03a480a25058a1           2.0
119009  179.99          40.59  8ab6855b9fe9b812cd03a480a25058a1           2.0
119010   68.50          18.36  dc9c59b4688062c25758c2be4cafc523           5.0

                      customer_unique_id customer_region  payment_sequential  \
0       7c396fd4830fd04220f754e42b4e5bff              SP                 1.0
1       7c396fd4830fd04220f754e42b4e5bff              SP                 3.0
2       7c396fd4830fd04220f754e42b4e5bff              SP                 2.0
3       af07308b275d755c9edb36a90c618231              BA                 1.0
4       3a653a41f6f9fc3d2a113cf8398680e8              GO                 1.0
...                                  ...             ...                 ...
119006  da62f9e57a76d978d02ab5362c509660              SP                 1.0
119007  737520a9aad80b3fbbdad19b66b37b30              BA                 1.0
119008  5097a5312c8b157bb7be58ae360ef43c              RJ                 1.0
119009  5097a5312c8b157bb7be58ae360ef43c              RJ                 1.0
119010  60350aa974b26ff12caad89e55993bd6              PR                 1.0

       payment_type  payment_installments  payment_value  \
0       credit_card                   1.0          18.12
1           voucher                   1.0           2.00
2           voucher                   1.0          18.59
3            boleto                   1.0         141.46
4       credit_card                   3.0         179.12
...             ...                   ...            ...
119006  credit_card                   3.0         195.00
119007  credit_card                   5.0         271.01
119008  credit_card                   4.0         441.16
119009  credit_card                   4.0         441.16
119010   debit_card                   1.0          86.86

         product_category_name  product_description_lenght  product_photos_qty
0        utilidades_domesticas                       268.0                 4.0
1        utilidades_domesticas                       268.0                 4.0
2        utilidades_domesticas                       268.0                 4.0
3                   perfumaria                       178.0                 1.0
4                   automotivo                       232.0                 1.0
...                        ...                         ...                 ...
119006                   bebes                       828.0                 4.0
119007      eletrodomesticos_2                       500.0                 2.0
119008  informatica_acessorios                      1893.0                 1.0
119009  informatica_acessorios                      1893.0                 1.0
119010            beleza_saude                       569.0                 1.0

[119011 rows x 20 columns]>

In [42]:
df.duplicated().value_counts()

False    108382
True      10629
Name: count, dtype: int64

In [43]:
print(df.duplicated)
df.duplicated

<bound method DataFrame.duplicated of                                 order_id                       customer_id  \
0       e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1       e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
2       e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
3       53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
4       47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
...                                  ...                               ...
119006  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7
119007  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c
119008  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
119009  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
119010  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24

       order_status order_purchase_timestamp order_delivered_customer_date  \
0         delivered      2017-10-02 10:56:33           2017-10-10 21:25:13
1         delivered      2017-10-02 10:56:33           2017-10-10 21:25:13
2         delivered      2017-10-02 10:56:33           2017-10-10 21:25:13
3         delivered      2018-07-24 20:41:37           2018-08-07 15:27:45
4         delivered      2018-08-08 08:38:49           2018-08-17 18:06:29
...             ...                      ...                           ...
119006    delivered      2018-02-06 12:58:58           2018-02-28 17:37:56
119007    delivered      2017-08-27 14:46:43           2017-09-21 11:24:17
119008    delivered      2018-01-08 21:28:27           2018-01-25 23:32:54
119009    delivered      2018-01-08 21:28:27           2018-01-25 23:32:54
119010    delivered      2018-03-08 20:57:30           2018-03-16 13:08:30

       order_estimated_delivery_date                        product_id  \
0                2017-10-18 00:00:00  87285b34884572647811a353c7ac498a
1                2017-10-18 00:00:00  87285b34884572647811a353c7ac498a
2                2017-10-18 00:00:00  87285b34884572647811a353c7ac498a
3                2018-08-13 00:00:00  595fac2a385ac33a80bd5114aec74eb8
4                2018-09-04 00:00:00  aa4383b373c6aca5d8797843e5594415
...                              ...                               ...
119006           2018-03-02 00:00:00  f1d4ce8c6dd66c47bbaa8c6781c2a923
119007           2017-09-27 00:00:00  b80910977a37536adeddd63663f916ad
119008           2018-02-15 00:00:00  d1c427060a0f73f6b889a5c7c61f2ac4
119009           2018-02-15 00:00:00  d1c427060a0f73f6b889a5c7c61f2ac4
119010           2018-04-03 00:00:00  006619bbed68b000c8ba3f8725d5409e

         price  freight_value                         review_id  review_score  \
0        29.99           8.72  a54f0611adc9ed256b57ede6b6eb5114           4.0
1        29.99           8.72  a54f0611adc9ed256b57ede6b6eb5114           4.0
2        29.99           8.72  a54f0611adc9ed256b57ede6b6eb5114           4.0
3       118.70          22.76  8d5266042046a06655c8db133d120ba5           4.0
4       159.90          19.22  e73b67b67587f7644d5bd1a52deb1b01           5.0
...        ...            ...                               ...           ...
119006  174.90          20.10  29bb71b2760d0f876dfa178a76bc4734           4.0
119007  205.99          65.02  371579771219f6db2d830d50805977bb           5.0
119008  179.99          40.59  8ab6855b9fe9b812cd03a480a25058a1           2.0
119009  179.99          40.59  8ab6855b9fe9b812cd03a480a25058a1           2.0
119010   68.50          18.36  dc9c59b4688062c25758c2be4cafc523           5.0

                      customer_unique_id customer_region  payment_sequential  \
0       7c396fd4830fd04220f754e42b4e5bff              SP                 1.0
1       7c396fd4830fd04220f754e42b4e5bff              SP                 3.0
2       7c396fd4830fd04220f754e42b4e5bff              SP                 2.0
3       af07308b275d755c9edb36a90c618231              BA                 1.0
4       3a653a41f6f9fc3d2a113cf8398680e8              GO                 1.0
...                                  ...             ...                 ...
119006  da62f9e57a76d978d02ab5362c509660              SP                 1.0
119007  737520a9aad80b3fbbdad19b66b37b30              BA                 1.0
119008  5097a5312c8b157bb7be58ae360ef43c              RJ                 1.0
119009  5097a5312c8b157bb7be58ae360ef43c              RJ                 1.0
119010  60350aa974b26ff12caad89e55993bd6              PR                 1.0

       payment_type  payment_installments  payment_value  \
0       credit_card                   1.0          18.12
1           voucher                   1.0           2.00
2           voucher                   1.0          18.59
3            boleto                   1.0         141.46
4       credit_card                   3.0         179.12
...             ...                   ...            ...
119006  credit_card                   3.0         195.00
119007  credit_card                   5.0         271.01
119008  credit_card                   4.0         441.16
119009  credit_card                   4.0         441.16
119010   debit_card                   1.0          86.86

         product_category_name  product_description_lenght  product_photos_qty
0        utilidades_domesticas                       268.0                 4.0
1        utilidades_domesticas                       268.0                 4.0
2        utilidades_domesticas                       268.0                 4.0
3                   perfumaria                       178.0                 1.0
4                   automotivo                       232.0                 1.0
...                        ...                         ...                 ...
119006                   bebes                       828.0                 4.0
119007      eletrodomesticos_2                       500.0                 2.0
119008  informatica_acessorios                      1893.0                 1.0
119009  informatica_acessorios                      1893.0                 1.0
119010            beleza_saude                       569.0                 1.0

[119011 rows x 20 columns]>

<bound method DataFrame.duplicated of                                 order_id                       customer_id  \
0       e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1       e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
2       e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
3       53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
4       47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
...                                  ...                               ...
119006  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7
119007  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c
119008  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
119009  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
119010  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24

       order_status order_purchase_timestamp order_delivered_customer_date  \
0         delivered      2017-10-02 10:56:33           2017-10-10 21:25:13
1         delivered      2017-10-02 10:56:33           2017-10-10 21:25:13
2         delivered      2017-10-02 10:56:33           2017-10-10 21:25:13
3         delivered      2018-07-24 20:41:37           2018-08-07 15:27:45
4         delivered      2018-08-08 08:38:49           2018-08-17 18:06:29
...             ...                      ...                           ...
119006    delivered      2018-02-06 12:58:58           2018-02-28 17:37:56
119007    delivered      2017-08-27 14:46:43           2017-09-21 11:24:17
119008    delivered      2018-01-08 21:28:27           2018-01-25 23:32:54
119009    delivered      2018-01-08 21:28:27           2018-01-25 23:32:54
119010    delivered      2018-03-08 20:57:30           2018-03-16 13:08:30

       order_estimated_delivery_date                        product_id  \
0                2017-10-18 00:00:00  87285b34884572647811a353c7ac498a
1                2017-10-18 00:00:00  87285b34884572647811a353c7ac498a
2                2017-10-18 00:00:00  87285b34884572647811a353c7ac498a
3                2018-08-13 00:00:00  595fac2a385ac33a80bd5114aec74eb8
4                2018-09-04 00:00:00  aa4383b373c6aca5d8797843e5594415
...                              ...                               ...
119006           2018-03-02 00:00:00  f1d4ce8c6dd66c47bbaa8c6781c2a923
119007           2017-09-27 00:00:00  b80910977a37536adeddd63663f916ad
119008           2018-02-15 00:00:00  d1c427060a0f73f6b889a5c7c61f2ac4
119009           2018-02-15 00:00:00  d1c427060a0f73f6b889a5c7c61f2ac4
119010           2018-04-03 00:00:00  006619bbed68b000c8ba3f8725d5409e

         price  freight_value                         review_id  review_score  \
0        29.99           8.72  a54f0611adc9ed256b57ede6b6eb5114           4.0
1        29.99           8.72  a54f0611adc9ed256b57ede6b6eb5114           4.0
2        29.99           8.72  a54f0611adc9ed256b57ede6b6eb5114           4.0
3       118.70          22.76  8d5266042046a06655c8db133d120ba5           4.0
4       159.90          19.22  e73b67b67587f7644d5bd1a52deb1b01           5.0
...        ...            ...                               ...           ...
119006  174.90          20.10  29bb71b2760d0f876dfa178a76bc4734           4.0
119007  205.99          65.02  371579771219f6db2d830d50805977bb           5.0
119008  179.99          40.59  8ab6855b9fe9b812cd03a480a25058a1           2.0
119009  179.99          40.59  8ab6855b9fe9b812cd03a480a25058a1           2.0
119010   68.50          18.36  dc9c59b4688062c25758c2be4cafc523           5.0

                      customer_unique_id customer_region  payment_sequential  \
0       7c396fd4830fd04220f754e42b4e5bff              SP                 1.0
1       7c396fd4830fd04220f754e42b4e5bff              SP                 3.0
2       7c396fd4830fd04220f754e42b4e5bff              SP                 2.0
3       af07308b275d755c9edb36a90c618231              BA                 1.0
4       3a653a41f6f9fc3d2a113cf8398680e8              GO                 1.0
...                                  ...             ...                 ...
119006  da62f9e57a76d978d02ab5362c509660              SP                 1.0
119007  737520a9aad80b3fbbdad19b66b37b30              BA                 1.0
119008  5097a5312c8b157bb7be58ae360ef43c              RJ                 1.0
119009  5097a5312c8b157bb7be58ae360ef43c              RJ                 1.0
119010  60350aa974b26ff12caad89e55993bd6              PR                 1.0

       payment_type  payment_installments  payment_value  \
0       credit_card                   1.0          18.12
1           voucher                   1.0           2.00
2           voucher                   1.0          18.59
3            boleto                   1.0         141.46
4       credit_card                   3.0         179.12
...             ...                   ...            ...
119006  credit_card                   3.0         195.00
119007  credit_card                   5.0         271.01
119008  credit_card                   4.0         441.16
119009  credit_card                   4.0         441.16
119010   debit_card                   1.0          86.86

         product_category_name  product_description_lenght  product_photos_qty
0        utilidades_domesticas                       268.0                 4.0
1        utilidades_domesticas                       268.0                 4.0
2        utilidades_domesticas                       268.0                 4.0
3                   perfumaria                       178.0                 1.0
4                   automotivo                       232.0                 1.0
...                        ...                         ...                 ...
119006                   bebes                       828.0                 4.0
119007      eletrodomesticos_2                       500.0                 2.0
119008  informatica_acessorios                      1893.0                 1.0
119009  informatica_acessorios                      1893.0                 1.0
119010            beleza_saude                       569.0                 1.0

[119011 rows x 20 columns]>

去除重复行（基于订单号、产品号、付款方式和支付价值）

In [44]:
# Remove duplicate rows
df_cleaned = df.drop_duplicates(subset=['order_id', 'product_id', 'payment_type', 'payment_value'])
df_cleaned
#print(df_cleaned.head())
#print(df_cleaned.describe())
#print(df_cleaned.duplicated().value_counts())

,order_id,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,product_id,price,freight_value,review_id,review_score,customer_unique_id,customer_region,payment_sequential,payment_type,payment_installments,payment_value,product_category_name,product_description_lenght,product_photos_qty
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18 00:00:00,87285b34884572647811a353c7ac498a,29.99,8.72,a54f0611adc9ed256b57ede6b6eb5114,4.0,7c396fd4830fd04220f754e42b4e5bff,SP,1.0,credit_card,1.0,18.12,utilidades_domesticas,268.0,4.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18 00:00:00,87285b34884572647811a353c7ac498a,29.99,8.72,a54f0611adc9ed256b57ede6b6eb5114,4.0,7c396fd4830fd04220f754e42b4e5bff,SP,3.0,voucher,1.0,2.00,utilidades_domesticas,268.0,4.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18 00:00:00,87285b34884572647811a353c7ac498a,29.99,8.72,a54f0611adc9ed256b57ede6b6eb5114,4.0,7c396fd4830fd04220f754e42b4e5bff,SP,2.0,voucher,1.0,18.59,utilidades_domesticas,268.0,4.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-08-07 15:27:45,2018-08-13 00:00:00,595fac2a385ac33a80bd5114aec74eb8,118.70,22.76,8d5266042046a06655c8db133d120ba5,4.0,af07308b275d755c9edb36a90c618231,BA,1.0,boleto,1.0,141.46,perfumaria,178.0,1.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-17 18:06:29,2018-09-04 00:00:00,aa4383b373c6aca5d8797843e5594415,159.90,19.22,e73b67b67587f7644d5bd1a52deb1b01,5.0,3a653a41f6f9fc3d2a113cf8398680e8,GO,1.0,credit_card,3.0,179.12,automotivo,232.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119005,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-17 15:08:01,2017-03-28 00:00:00,ac35486adb7b02598c182c2ff2e05254,72.00,13.08,e262b3f92d1ce917aa412a9406cf61a6,5.0,6359f309b166b0196dbf7ad2ac62bb5a,SP,1.0,credit_card,3.0,85.08,beleza_saude,1517.0,1.0
119006,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-28 17:37:56,2018-03-02 00:00:00,f1d4ce8c6dd66c47bbaa8c6781c2a923,174.90,20.10,29bb71b2760d0f876dfa178a76bc4734,4.0,da62f9e57a76d978d02ab5362c509660,SP,1.0,credit_card,3.0,195.00,bebes,828.0,4.0
119007,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-09-21 11:24:17,2017-09-27 00:00:00,b80910977a37536adeddd63663f916ad,205.99,65.02,371579771219f6db2d830d50805977bb,5.0,737520a9aad80b3fbbdad19b66b37b30,BA,1.0,credit_card,5.0,271.01,eletrodomesticos_2,500.0,2.0
119008,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-25 23:32:54,2018-02-15 00:00:00,d1c427060a0f73f6b889a5c7c61f2ac4,179.99,40.59,8ab6855b9fe9b812cd03a480a25058a1,2.0,5097a5312c8b157bb7be58ae360ef43c,RJ,1.0,credit_card,4.0,441.16,informatica_acessorios,1893.0,1.0
119010,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-16 13:08:30,2018-04-03 00:00:00,006619bbed68b000c8ba3f8725d5409e,68.50,18.36,dc9c59b4688062c25758c2be4cafc523,5.0,60350aa974b26ff12caad89e55993bd6,PR,1.0,debit_card,1.0,86.86,beleza_saude,569.0,1.0

In [45]:
df_cleaned.to_csv('Joined_Dataframe_remove_duplicates.csv', sep=",")

In [46]:
df_cleaned.isnull().sum()

order_id                             0
customer_id                          0
order_status                         0
order_purchase_timestamp             0
order_delivered_customer_date     3139
order_estimated_delivery_date        0
product_id                         811
price                              811
freight_value                      811
review_id                        10641
review_score                     10641
customer_unique_id                   0
customer_region                      0
payment_sequential                   1
payment_type                         1
payment_installments                 1
payment_value                        1
product_category_name             2335
product_description_lenght        2335
product_photos_qty                2335
dtype: int64

In [47]:
data = df_cleaned.copy()

In [64]:
#print(data_encoded.head())
data_encoded.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,order_id,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,product_id,...,product_category_name_portateis_cozinha_e_preparadores_de_alimentos.1,product_category_name_relogios_presentes.1,product_category_name_seguros_e_servicos.1,product_category_name_sinalizacao_e_seguranca.1,product_category_name_tablets_impressao_imagem.1,product_category_name_telefonia.1,product_category_name_telefonia_fixa.1,product_category_name_utilidades_domesticas.1,product_category_name_nan.1,payment_count
0,0,0,0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18 00:00:00,87285b34884572647811a353c7ac498a,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3
1,1,1,1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18 00:00:00,87285b34884572647811a353c7ac498a,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3
2,2,2,2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18 00:00:00,87285b34884572647811a353c7ac498a,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3
3,3,3,3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-08-07 15:27:45,2018-08-13 00:00:00,595fac2a385ac33a80bd5114aec74eb8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,4,4,4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-17 18:06:29,2018-09-04 00:00:00,aa4383b373c6aca5d8797843e5594415,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [50]:
data_encoded.to_csv('Joined_Dataframe_remove_duplicates_add_features.csv', sep=",")

In [51]:
import pandas as pd

data_encoded=pd.read_csv('Joined_Dataframe_remove_duplicates_add_features.csv')
data_encoded.head()

print(data_encoded.columns)
print(data_encoded['payment_sequential'].isnull().sum())

data_agg=data_encoded.copy()

Index(['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0', 'order_id', 'customer_id',
       'order_status', 'order_purchase_timestamp',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'product_id',
       ...
       'product_category_name_portateis_casa_forno_e_cafe.1',
       'product_category_name_portateis_cozinha_e_preparadores_de_alimentos.1',
       'product_category_name_relogios_presentes.1',
       'product_category_name_seguros_e_servicos.1',
       'product_category_name_sinalizacao_e_seguranca.1',
       'product_category_name_tablets_impressao_imagem.1',
       'product_category_name_telefonia.1',
       'product_category_name_telefonia_fixa.1',
       'product_category_name_utilidades_domesticas.1',
       'product_category_name_nan.1'],
      dtype='object', length=241)
1

In [48]:
import pandas as pd

# 读取csv文件Joined_Dataframe_remove_duplicates_add_features
data = pd.read_csv('Joined_Dataframe_remove_duplicates_add_features.csv')

# 暂时去掉price,freight_value,customer_id,price,freight_value,review_id,customer_unique_id
# data.drop(['price','freight_value','customer_id','price','freight_value','review_id','customer_unique_id'],axis=1, inplace=True)
# data

# 将时间列转换为 datetime 格式
# data['order_purchase_timestamp'] = pd.to_datetime(data['order_purchase_timestamp'], format='%Y-%m-%d %H:%M:%S')
# data['order_delivered_customer_date'] = pd.to_datetime(data['order_delivered_customer_date'], format='%Y-%m-%d %H:%M:%S')
# data['order_estimated_delivery_date'] = pd.to_datetime(data['order_estimated_delivery_date'], format='%Y-%m-%d %H:%M:%S')

# 计算购买时间和收货时间之间的差，单位是天
# data['delivery_diff'] = (data['order_delivered_customer_date'] - data['order_purchase_timestamp']).dt.days

# 创建二元变量，判断收货时间是否晚于预计送达时间
# data['is_late'] = (data['order_delivered_customer_date'].dt.date > data['order_estimated_delivery_date'].dt.date).astype(int)
# 创建二元变量，判断是否分期
# data['is_installments'] = (data['payment_installments'] > 1).astype(int)

# 创建二元变量OneHotEncoding
from sklearn.preprocessing import OneHotEncoder

# 创建 OneHotEncoder 对象
encoder = OneHotEncoder(sparse_output=False)

# 对需要进行 One-Hot 编码的列进行编码
categorical_cols = ['order_status', 'customer_region', 'product_category_name']
encoded_data = encoder.fit_transform(data[categorical_cols])

# 获取编码后的特征名称
feature_names = encoder.get_feature_names_out(categorical_cols)

# 将编码后的结果转换为 DataFrame，并设置列名
encoded_df = pd.DataFrame(encoded_data, columns=feature_names)

# 将编码后的列合并到原始数据集中
data_encoded = pd.concat([data, encoded_df], axis=1)

In [56]:
# def process_payment_value(agg_group):
#     # 提取聚合后的数据
#     payment_value_sum = agg_group['payment_value']
#     payment_sequential_max = agg_group['payment_sequential']
#     payment_count = agg_group['payment_count']

#     # 根据 payment_count 的值进行计算
#     if payment_count == 1:
#         return payment_value_sum  # 如果只有一个付款序列，payment_value不变
#     else:
#         adjustment_factor = payment_count / payment_sequential_max
#         return payment_value_sum / adjustment_factor

# # 先计算 'payment_count'，即每个 'order_id' 中 'payment_sequential' 的计数
# data_encoded['payment_count'] = data_encoded.groupby('order_id')['payment_sequential'].transform('count')

# # 按 'order_id' 分组
# df_agg = data_encoded.groupby('order_id').agg({
#     'payment_sequential': 'max',  # 对 'payment_sequential' 使用最大值聚合
#     'payment_value': 'sum',
#     'payment_count': 'first',
#     'order_status': 'first',
#     'order_purchase_timestamp': 'first',
#     'order_delivered_customer_date': 'first',
#     'order_estimated_delivery_date': 'first',
#     'product_id': 'first',
#     'payment_installments': 'first',
#     'review_score': 'first',  # 取评分的第一个值
#     'product_category_name': 'first',  # 保留订单中的第一个商品类别
#     'customer_region': 'first',  # 保留订单的第一个客户区域
#     'product_photos_qty': 'mean',  # 保留订单的第一个商品照片数量
#     'product_description_lenght': 'mean',  # 保留订单的第一个商品描述长度
#     'delivery_diff': 'first',  # 保留订单的第一个购买时间和收货时间之间的差
#     'is_late': 'first',  # 保留订单的第一个收货时间是否晚于预计送达时间
#     'is_installments': 'first',
#     'order_status_approved': 'first',
#     'order_status_created': 'first',
#     'order_status_canceled': 'first',
#     'order_status_delivered': 'first',
#     'order_status_invoiced': 'first',
#     'order_status_processing': 'first',
#     'order_status_shipped': 'first',
#     'order_status_unavailable': 'first',
#     'customer_region_AC': 'first',
#     'customer_region_AL': 'first',
#     'customer_region_AM': 'first',
#     'customer_region_AP': 'first',
#     'customer_region_BA': 'first',
#     'customer_region_CE': 'first',
#     'customer_region_DF': 'first',
#     'customer_region_ES': 'first',
#     'customer_region_GO': 'first',
#     'customer_region_MA': 'first',
#     'customer_region_MG': 'first',
#     'customer_region_MS': 'first',
#     'customer_region_MT': 'first',
#     'customer_region_PA': 'first',
#     'customer_region_PB': 'first',
#     'customer_region_PE': 'first',
#     'customer_region_PI': 'first',
#     'customer_region_PR': 'first',
#     'customer_region_RJ': 'first',
#     'customer_region_RN': 'first',
#     'customer_region_RO': 'first',
#     'customer_region_RR': 'first',
#     'customer_region_RS': 'first',
#     'customer_region_SC': 'first',
#     'customer_region_SE': 'first',
#     'customer_region_SP': 'first',
#     'customer_region_TO': 'first',
#     'product_category_name_agro_industria_e_comercio': 'first',
#     'product_category_name_alimentos': 'first',
#     'product_category_name_alimentos_bebidas': 'first',
#     'product_category_name_artes': 'first',
#     'product_category_name_artes_e_artesanato': 'first',
#     'product_category_name_artigos_de_festas': 'first',
#     'product_category_name_artigos_de_natal': 'first',
#     'product_category_name_audio': 'first',
#     'product_category_name_automotivo': 'first',
#     'product_category_name_bebes': 'first',
#     'product_category_name_bebidas': 'first',
#     'product_category_name_beleza_saude': 'first',
#     'product_category_name_brinquedos': 'first',
#     'product_category_name_cama_mesa_banho': 'first',
#     'product_category_name_casa_conforto': 'first',
#     'product_category_name_casa_conforto_2': 'first',
#     'product_category_name_casa_construcao': 'first',
#     'product_category_name_cds_dvds_musicais': 'first',
#     'product_category_name_cine_foto': 'first',
#     'product_category_name_climatizacao': 'first',
#     'product_category_name_consoles_games': 'first',
#     'product_category_name_construcao_ferramentas_construcao': 'first',
#     'product_category_name_construcao_ferramentas_ferramentas': 'first',
#     'product_category_name_construcao_ferramentas_iluminacao': 'first',
#     'product_category_name_construcao_ferramentas_jardim': 'first',
#     'product_category_name_construcao_ferramentas_seguranca': 'first',
#     'product_category_name_cool_stuff': 'first',
#     'product_category_name_dvds_blu_ray': 'first',
#     'product_category_name_eletrodomesticos': 'first',
#     'product_category_name_eletrodomesticos_2': 'first',
#     'product_category_name_eletronicos': 'first',
#     'product_category_name_eletroportateis': 'first',
#     'product_category_name_esporte_lazer': 'first',
#     'product_category_name_fashion_bolsas_e_acessorios': 'first',
#     'product_category_name_fashion_calcados': 'first',
#     'product_category_name_fashion_esporte': 'first',
#     'product_category_name_fashion_roupa_feminina': 'first',
#     'product_category_name_fashion_roupa_infanto_juvenil': 'first',
#     'product_category_name_fashion_roupa_masculina': 'first',
#     'product_category_name_fashion_underwear_e_moda_praia': 'first',
#     'product_category_name_ferramentas_jardim': 'first',
#     'product_category_name_flores': 'first',
#     'product_category_name_fraldas_higiene': 'first',
#     'product_category_name_industria_comercio_e_negocios': 'first',
#     'product_category_name_informatica_acessorios': 'first',
#     'product_category_name_instrumentos_musicais': 'first',
#     'product_category_name_la_cuisine': 'first',
#     'product_category_name_livros_importados': 'first',
#     'product_category_name_livros_interesse_geral': 'first',
#     'product_category_name_livros_tecnicos': 'first',
#     'product_category_name_malas_acessorios': 'first',
#     'product_category_name_market_place': 'first',
#     'product_category_name_moveis_colchao_e_estofado': 'first',
#     'product_category_name_moveis_cozinha_area_de_servico_jantar_e_jardim': 'first',
#     'product_category_name_moveis_decoracao': 'first',
#     'product_category_name_moveis_escritorio': 'first',
#     'product_category_name_moveis_quarto': 'first',
#     'product_category_name_moveis_sala': 'first',
#     'product_category_name_musica': 'first',
#     'product_category_name_papelaria': 'first',
#     'product_category_name_pc_gamer': 'first',
#     'product_category_name_pcs': 'first',
#     'product_category_name_perfumaria': 'first',
#     'product_category_name_pet_shop': 'first',
#     'product_category_name_portateis_casa_forno_e_cafe': 'first',
#     'product_category_name_portateis_cozinha_e_preparadores_de_alimentos': 'first',
#     'product_category_name_flores': 'first',
#     'product_category_name_relogios_presentes': 'first',
#     'product_category_name_seguros_e_servicos': 'first',
#     'product_category_name_sinalizacao_e_seguranca': 'first',
#     'product_category_name_tablets_impressao_imagem': 'first',
#     'product_category_name_telefonia': 'first',
#     'product_category_name_telefonia_fixa': 'first',
#     'product_category_name_utilidades_domesticas': 'first',
#     'product_category_name_nan': 'first'
# }).reset_index()

# # 现在应用 process_payment_value 来调整 payment_value
# df_agg['payment_value'] = df_agg.apply(process_payment_value, axis=1)

# # 显示结果
# df_agg

# # 导出文件
# df_agg.to_csv('Joined_Dataframe_remove_duplicates_add_features_agg.csv', sep=",")

KeyError: "Column(s) ['delivery_diff', 'is_installments', 'is_late'] do not exist"

In [ ]:
df_agg.to_csv('Joined_Dataframe_remove_duplicates_add_features_agg.csv', sep=",")

In [ ]:
# 显示结果
df_agg

,order_id,payment_sequential,payment_value,payment_count,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,product_id,payment_installments,...,product_category_name_portateis_casa_forno_e_cafe,product_category_name_portateis_cozinha_e_preparadores_de_alimentos,product_category_name_relogios_presentes,product_category_name_seguros_e_servicos,product_category_name_sinalizacao_e_seguranca,product_category_name_tablets_impressao_imagem,product_category_name_telefonia,product_category_name_telefonia_fixa,product_category_name_utilidades_domesticas,product_category_name_nan
0,00010242fe8c5a6d1ba2dd792cb16214,1,72.19,1,delivered,2017/9/13 8:59,2017/9/20 23:43,2017/9/29,4244733e06e7ecb4970a6e2683c13e61,2.0,...,0,0,0,0,0,0,0,0,0,0
1,00018f77f2f0320c557190d7a144bdd3,1,259.83,1,delivered,2017/4/26 10:53,2017/5/12 16:04,2017/5/15,e5f2d52b802189ee658865ca93d83a8f,3.0,...,0,0,0,0,0,0,0,0,0,0
2,000229ec398224ef6ca0657da4fc703e,1,216.87,1,delivered,2018/1/14 14:33,2018/1/22 13:19,2018/2/5,c777355d18b72b67abbeef9df44fd0fd,5.0,...,0,0,0,0,0,0,0,0,0,0
3,00024acbcdf0a6daa1e931b038114c75,1,25.78,1,delivered,2018/8/8 10:00,2018/8/14 13:32,2018/8/20,7634da152a4610f1595efa32f14722fc,2.0,...,0,0,0,0,0,0,0,0,0,0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,218.04,1,delivered,2017/2/4 13:57,2017/3/1 16:42,2017/3/17,ac6c3623068f30de03045865e4e10089,3.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,fffc94f6ce00a00581880bf54a75a037,1,343.40,1,delivered,2018/4/23 13:57,2018/5/10 22:56,2018/5/18,4aa6014eceb682077f9dc4bffebc05b0,1.0,...,0,0,0,0,0,0,0,0,1,0
99437,fffcd46ef2263f404302a634eb57f7eb,1,386.53,1,delivered,2018/7/14 10:26,2018/7/23 20:31,2018/8/1,32e07fd915822b0765e448c4dd74c828,1.0,...,0,0,0,0,0,0,0,0,0,0
99438,fffce4705a9662cd70adb13d4a31832d,1,116.85,1,delivered,2017/10/23 17:07,2017/10/28 12:22,2017/11/10,72a30483855e2eafc67aee5dc2560482,3.0,...,0,0,0,0,0,0,0,0,0,0
99439,fffe18544ffabc95dfada21779c9644f,1,64.71,1,delivered,2017/8/14 23:02,2017/8/16 21:59,2017/8/25,9c422a519119dcad7575db5af1ba540e,3.0,...,0,0,0,0,0,0,0,0,0,0
99440,fffe41c64501cc87c801fd61db3f6244,1,55.79,1,delivered,2018/6/9 17:00,2018/6/14 17:56,2018/6/28,350688d9dc1e75ff97be326363655e01,1.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df_agg.to_csv('Joined_Dataframe_remove_duplicates_add_features_agg.csv', sep=",")

In [ ]:
# Rename columns for clarity.
df_agg.rename(columns={
    'payment_value': 'Totalpayment',
    'payment_sequential': 'Maxsequential',
    'product_photos_qty': 'Meanphotosquantity',
    'product_description_lenght': 'Meandescriptionlength'
}, inplace=True)

In [ ]:
# drop null value
df.dropna(inplace=True)
df.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_delivered_customer_date    0
order_estimated_delivery_date    0
product_id                       0
price                            0
freight_value                    0
review_score                     0
customer_region                  0
payment_type                     0
payment_installments             0
payment_value                    0
product_category_name            0
product_photos_qty               0
product_weight_g                 0
dtype: int64

In [ ]:
df.describe()

,price,freight_value,review_score,payment_installments,payment_value,product_photos_qty,product_weight_g
count,102762.000000,102762.000000,102762.000000,102762.000000,102762.000000,102762.000000,102762.000000
mean,119.790588,20.001062,4.066279,2.947228,172.312457,2.205076,2105.440513
std,181.870031,15.688503,1.359080,2.783094,266.611123,1.715275,3756.033157
min,0.850000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
25%,39.900000,13.080000,4.000000,1.000000,61.010000,1.000000,300.000000
50%,74.900000,16.300000,5.000000,2.000000,108.085000,1.000000,700.000000
75%,132.900000,21.180000,5.000000,4.000000,189.645000,3.000000,1800.000000
max,6735.000000,409.680000,5.000000,24.000000,13664.080000,20.000000,40425.000000

In [ ]:
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,payment_installments,payment_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,1.0,18.12,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,1.0,2.00,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,1.0,18.59,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,595fac2a385ac33a80bd5114aec74eb8,...,1.0,141.46,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,aa4383b373c6aca5d8797843e5594415,...,3.0,179.12,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119006,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1.0,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,3.0,195.00,bebes,52.0,828.0,4.0,4950.0,40.0,10.0,40.0
119007,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1.0,b80910977a37536adeddd63663f916ad,...,5.0,271.01,eletrodomesticos_2,51.0,500.0,2.0,13300.0,32.0,90.0,22.0
119008,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,1.0,d1c427060a0f73f6b889a5c7c61f2ac4,...,4.0,441.16,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
119009,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2.0,d1c427060a0f73f6b889a5c7c61f2ac4,...,4.0,441.16,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
119010,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,006619bbed68b000c8ba3f8725d5409e,...,1.0,86.86,beleza_saude,45.0,569.0,1.0,150.0,16.0,7.0,15.0

In [ ]:
df.to_csv('Joined_Dataframe.csv', sep=",")

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('Joined_Dataframe.csv')

In [ ]:
#df.duplicated.to_csv('duplicated.csv')

AttributeError: 'function' object has no attribute 'to_csv'

**Feature engineering**

In [ ]:
df = pd.read_csv('Joined_Dataframe_remove_duplicates.csv')
df.head()

# Feature engineering

invoice_agg = df.groupby('Invoice').agg({
    'Quantity': 'sum',
    'TotalAmount': 'sum',
    'StockCode': 'nunique',
    'Canceled': 'max',
    'Country': 'first'
}).reset_index()

# Rename columns for clarity.
invoice_agg.rename(columns={
    'Quantity': 'TotalQuantity',
    'StockCode': 'NumItems'
}, inplace=True)

# Create an average unit price column (handling division by zero).
invoice_agg['AvgUnitPrice'] = invoice_agg.apply(
    lambda row: row['TotalAmount'] / row['TotalQuantity'] if row['TotalQuantity'] != 0 else 0, axis=1)

print("\nAggregated (invoice-level) data shape:", invoice_agg.shape)
print(invoice_agg.head())

# For our classification, select only the numeric features and the target.
data_model = invoice_agg[['TotalQuantity', 'TotalAmount', 'NumItems', 'AvgUnitPrice', 'Canceled']]

print("\nData description for modeling:")
print(data_model.describe())

# #orders_feature
df['delivery_time'] = (pd.to_datetime(df['order_delivered_customer_date']) - pd.to_datetime(df['order_purchase_timestamp'])).dt.days
df['is_late_delivery'] = (pd.to_datetime(df['order_delivered_customer_date']) > pd.to_datetime(df['order_estimated_delivery_date'])).astype(int)
# Customer Characteristics
df['customer_order_count'] = df.groupby('customer_id')['order_id'].transform('count')
df['customer_avg_review_score'] = df.groupby('customer_id')['review_score'].transform('mean')
# Payment way
df['payment_method_count'] = df.groupby('customer_id')['payment_value'].transform('count')
df['payment_method_avg_value'] = df.groupby('customer_id')['payment_value'].transform('mean')

**Visualising the Data**

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.pairplot(data = df[['AGE','RM','CRIM','MV']],diag_kind='hist')#diag_kind{‘auto’, ‘hist’, ‘kde’, None}